# Configuration for generate_qa_for_upsampled_consistent.py
base_output_dir: /project/cc-20250120231604/ssd/users/kwsu/research/dsllm/dsllm/data
baseline_qa_paths:
  train: "{base_output_dir}/stage_2_compare_buffer/300seconds_100DS/train/capture24_train_qa_stage2_cls.json"
  test: "{base_output_dir}/stage_2_compare_buffer/300seconds_100DS/test/capture24_test_qa_stage2_cls.json"
  val: "{base_output_dir}/stage_2_compare_buffer/300seconds_100DS/val/capture24_val_qa_stage2_cls.json"
upsampled_tag: 300seconds_100DS_upsampled_from_1000DS
upsampled_dir: "{base_output_dir}/stage_2_upsampled_constraint/{upsampled_tag}"
splits:
  - train
  - test 
  - val 